### ISSUE TITLE
Double click in bottom navigation

### ISSUE THREAD

**Issue by khaledhnAbusair** [oneHamidreza/MeowBottomNavigation#56]
**Hello,

When double click in a bottom this exception will appear , can u help me please ?**

 

> java.lang.NullPointerException: Attempt to invoke interface method 'void com.etebarian.meowbottomnavigation.MeowBottomNavigation$ReselectListener.onReselectItem(com.etebarian.meowbottomnavigation.MeowBottomNavigation$Model)' on a null object reference
>         at com.etebarian.meowbottomnavigation.MeowBottomNavigation$1.onClickItem(MeowBottomNavigation.java:277)
>         at com.etebarian.meowbottomnavigation.MeowBottomNavigationCell$2.onClick(MeowBottomNavigationCell.java:330)
>         at android.view.View.performClick(View.java:7189)
>         at android.view.View.performClickInternal(View.java:7163)
>         at android.view.View.access$3500(View.java:821)
>         at android.view.View$PerformClick.run(View.java:27579)
>         at android.os.Handler.handleCallback(Handler.java:888)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at android.os.Looper.loop(Looper.java:213)
>         at android.app.ActivityThread.main(ActivityThread.java:8147)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by khaledhnAbusair** [comment]
Thanks,i handle this by call this method setOnReselectListener
